url: http://lavictrola.lib13.com
baseurl: http://lavictrola.lib13.com

# Site settings
title: La Victrola
email: vaibhavb@lib13.com
description: "The People Art."
author: "Vaibhav Bhandari"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fe5e36
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lavictrola
  - title: facebook
    url: http://facebook.com/lavictrola
  - title: github
    url: http://github.com/lavictrola


# Build settings
markdown: kramdown
permalink: pretty
